### PR TITLE
Added method caching to XmlBuilder instances

### PR DESCRIPTION
**Pull request by barttenbrinke**
Hello,
first of all: I really love the xml builder. The interface is clean and the implementation is simple and clean.
There were however two things that I felt that needed some improvement:
- First commit: Moved all logic from method_missing to tag! function. As stated in the original comments on the method_missing: "method_missing should never be called directly" and it also should not have complex logic in it. This commit addresses this.
- Second commit:  This commit dynamically creates any method missed as an instance method on the XMLBuilder instance object. Because XML documents are usually very repetitive in nature, the next node will be handled by the new method instead of method_missing. As method_missing is very slow, this speeds up document generation significantly.

Greetings, Bart ten Brinke

### CODE REVIEW

**Comment by jimweirich** [comment]
I like the changes proposed by this pull.

However,

(1) There is a reference to a bare Symbol in XmlBase.  It should be ::Symbol
(2) Is there any reason to NOT cache the files all the time.  If not, I would drop the cache_method_calls flag and make it unconditional.
(3) The test for non-caching method fails (I think its because defined? will check method missing, tho not sure).  If (2) is implemented, then this problem is moot.

**Comment by barttenbrinke** [comment]
1) Fixed
2) I could not think of any reason not to cache it either, but sometimes I don't think of every usecase.
3) I made it non-optional and so removed the test case.

**Comment by jimweirich** [comment]
Merged.  Should be available in 3.1.0

**Comment by jonkessler** [comment]
There's actually an issue with this method caching that I just ran into. I disabled it to fix the problem. The issue is that in cache_method_call in xmlbase.rb will crash if sym contains a character that is invalid in a method name, such as a hyphen (in our case). Perhaps this can be fixed by using define_method(sym) rather than def #{sym.to_s}?

**Comment by jimweirich** [comment]
How did you manage to get an invalid symbol to cache_method_call? It's only invoked from method_missing, so it seems like it would only get good methods.  Do you have a concrete example?

**Comment by jimweirich** [comment]
You weren't calling method_missing directly, were you?  If so, use the tag! method instead.

**Comment by jimweirich** [comment]
Reopening until we get resolution on this.

**Comment by jonkessler** [comment]
Sure, here are some minimal STRs:
1. Create a new Rails project with builder 3.0.1
2. Generate a model called WorkOrder
3. Open up the Rails console and run [WorkOrder.new].to_xml
This crashes with a syntax error. The culprit seems to be active_support/core_ext/array/conversions.rb line 158 (Rails 3.2.8). Specifically, the rename_key call on line 152 causes root to become 'work-orders'. Thus, when the call to method_missing is made on line 158, the method called is 'work-orders'. I really do think using define_method may be able to solve this with minimal trouble.

**Comment by jimweirich** [comment]
Ahh, I see. Rails is explicitly invoking method_missing.  Sigh.

Ok, I've got a handle on this.

**Comment by jimweirich** [comment]
Version 3.0.2 / 3.1.2 has the fix.

**Comment by jonkessler** [comment]
Awesome. Thanks for being super responsive.

**Pull request closed without merging**
